backend:
  # name: test-repo
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
i18n:
  structure: multiple_folders
  locales: [fr, en]
  default_locale: fr
collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "general"
    label: "General"
    delete: false
    editor:
      preview: false
    files:
      - name: "galleries"
        label: "Galleries"
        file: "meta/galleries.yml"
        description: "Galleries"
        fields:
          - name: galleries
            label: Galleries
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the gallery"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "Gallery name"
              - label: "Address"
                name: "address"
                widget: "markdown"
                hint: "Gallery complete address"
              - label: "Phone"
                name: "phone"
                widget: "string"
                hint: "Gallery Phone with country code (+33)"
              - label: "Email"
                name: "email"
                widget: "string"
                hint: "Gallery Email"
              - label: "Location"
                name: "location"
                widget: "map"
                hint: "Place the pin at the exact location of the Gallery"

  - name: "programme"
    i18n: true
    label: "Programme"
    folder: "src/pages/programme"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: true
      - label: "Month"
        name: "month"
        widget: "string"
        i18n: duplicate
        hint: "Ex: 6-16 Mai"
      - label: "Year"
        name: "year"
        widget: "string"
        i18n: duplicate
        hint: "Ex: 2021"
      - label: "Start Date"
        name: "start"
        widget: "date"
        i18n: duplicate
        hint: "Choose the start date of event. This serves only internally to arrange the events."
      - label: "Description"
        name: "description"
        widget: "markdown"
        i18n: true
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["now", "upcoming", "past"]
      - label: "Programme PDF"
        name: "file"
        widget: "file"
        default: "/uploads/programme_pdf.pdf"
        i18n: true
        media_library:
          config:
            multiple: true
      - label: "Galleries"
        name: "galleries"
        widget: list
        summary: "{{fields.galleries}}"
        field:
          label: "Galleries"
          name: "galleries"
          widget: "relation"
          collection: "general"
          file: "galleries"
          search_fields: ["galleries.*.name"]
          value_field: "galleries.*.name"
          display_fields: ["galleries.*.name"]
